import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  globalArray:string[]=
  ["Others",
  "42 Gears",
  "47 Billion",
  "Accelerize36 0",
  "Accenture",
  "Addverb Technologie s",
  "Adobe",
  "Adsys",
  "Affinsys",
  "Afford Medical Technologie s Private Limited",
  "Air Asia",
  "Airbnb",
  "Airoha Technology",
  "Amadeus",
  "Amagi Media Labs",
  "Amazon",
  "AMAZON INDIA",
  "American Express",
  "Apollo247",
  "App Dynamics",
  "AppsforBhar at",
  "AppViewX",
  "Arcesium",
  "Aspect Ratio",
  "asterdmheal thcare",
  "athenahealt h Technologie s Pvt Ltd",
  "Ather Energy",
  "Atlan",
  "Atlassian",
  "Audify Tech",
  "Avalara",
  "Axxela",
  "Bain Capability Network",
  "Bajaj Finserv",
  "BAKER HUGHES",
  "Barclays",
  "Becton Dickinson Technology",
  "BharatX",
  "BLACKROCK",
  "Blaize",
  "Blinkit (Grofers)",
  "Bluebird India R&D Center Pvt Ltd",
  "BMW india",
  "BNY Mellon",
  "BootNext",
  "Bosch Global Software Technologie s",
  "Broadridge Financial Solutions",
  "BYJU'S",
  "Caelius Consulting IT Services Private Limited",
  "Capgemini",
  "Capillary",
  "Capillary Technologie s",
  "CarWale",
  "CASA RETAIL AI",
  "Cashfree",
  "Celigo",
  "CHARGEBEE",
  "CISCO",
  "CITI Bank (CISPL)",
  "Clear Trail",
  "Clinicspot",
  "Cloudera",
  "Codemantra",
  "Cognizant",
  "Cogoport",
  "Commvault Systems Pvt LTD",
  "Consultadd",
  "ConveGeniu s",
  "Covetus LLC",
  "Cradlepoint",
  "CRED",
  "Credit Suisse",
  "CubexO Software",
  "Cure.fit",
  "Darwinbox",
  "Data Insights",
  "Databricks",
  "DE Shaw & Co",
  "Dell",
  "Dell Technologie s",
  "Deutsche Bank",
  "DevRev Cloud India",
  "Dish Network Technologie s",
  "Dotpe Pvt Ltd",
  "Dover Corporation",
  "Dozee",
  "Eaton",
  "Electronic Arts",
  "Electronic Arts, India",
  "Eli Lilly Services India Pvt. Ltd.",
  "Enphase Energy",
  "Ensuredit",
  "Enterprises Ltd",
  "Epicor Software Pvt Ltd.",
  "Epsilon",
  "Ericsson (R&D)",
  "Ericsson India Global Services",
  "Espressif",
  "Euler Motors",
  "Expedia Group",
  "ExxonMobil Services & Technology Private Limited",
  "EY -INDIA",
  "FABC LLC",
  "FamPay",
  "FAREPORTA L",
  "Fastenal",
  "Fidelity Investment",
  "Flexcar IDC",
  "FLIPKART NEEV INTERNSHIP",
  "Ford",
  "Forma AI",
  "Fractal Analytics",
  "Freo",
  "fujitsu",
  "Fundwave",
  "GalaxEye Space",
  "GalaxEye Space Solutions Limited",
  "GammaStack",
  "General Electric",
  "GENPACT",
  "Goldman Sachs",
  "Growisto",
  "Groww",
  "GSK Global Capability Center",
  "Gullak Money",
  "Harness",
  "HashedIn",
  "HAVELLS INDIA LIMITED",
  "Hella Infra Market Private Limited",
  "HelpShift",
  "Hewlett Packard Enterprise",
  "Hitachi Energy Technology and Services Pvt Limited",
  "HONASA CONSUMER PVT LTD (MAMA EARTH)",
  "Honeywell",
  "HONO.AI",
  "HSBC",
  "HSBC Technology India",
  "Human Holdings",
  "HyperVerge",
  "IAMNEO",
  "IBM",
  "ICICI Lombard GIC Ltd",
  "IDrive Software India Pvt Ltd",
  "Incedo",
  "Info Edge (Naukri)",
  "Infosys(HWI,InfyTQ)",
  "INSIGHTSOF TWARE",
  "Institutional Shareholder Services India Pvt. Ltd",
  "Intel India",
  "Ion Group",
  "ITILITE",
  "IVANTI",
  "Jio",
  "John Deere India Pvt. Ltd.",
  "Josh Software",
  "JP MORGAN CHASE",
  "Jubilant FoodWorks",
  "JUNGLEE GAMES",
  "JUSPAY",
  "Kaleyra",
  "KIMBERLY CLARK",
  "Kinaxis India Pvt Ltd",
  "Komprise India Private",
  "LATENTVIE W",
  "LEADSQUAR ED",
  "LetsTranspor t",
  "Linkedin",
  "Logitech",
  "LTI",
  "Luganodes",
  "Mad Street Den",
  "MAKEMYTRI P",
  "MAQ Software",
  "MathWorks India",
  "Maxlinear Technologie s",
  "McKinsey & Company",
  "Media.net",
  "Medtronic Engineering and Innovation Center",
  "Meesho",
  "Mercedes- Benz Research and Developmen t (MBRDI)",
  "Mesho",
  "Metafic",
  "Microchip Technology",
  "MICROFOCU S",
  "Microsoft",
  "Microsoft India",
  "MindRuby",
  "MONEYVIE W",
  "Morgan Stanley",
  "MulticoreWa re",
  "Nation with Namo",
  "Natwest Group",
  "Nav Tech Electronics India Pvt Ltd",
  "NielsenIQ",
  "NRI Fintech",
  "NTT India Digital Business Solutions Private LimioriginalArrayted",
  "Nuclei",
  "Nucleusteq",
  "nurture.farm",
  "Nutanix",
  "Nykaa",
  "OfBusiness",
  "OneShot.ai",
  "Oracle GBU",
  "Osmosys",
  "Oyo",
  "Ozone Cloud",
  "Palo Alto Networks",
  "PayPal",
  "PayU",
  "PepsiCo GBS",
  "Persistent(Martian)",
  "Persistent(OnCampus)",
  "Philips India Limited",
  "Philips Lighting (Signify)",
  "Pine Labs",
  "Plotline",
  "Pocketpills (Casahealth Tech Pvt Ltd)",
  "PolicyBazaar Insurance Brokers private limited",
  "Principal Global Services",
  "Private Limited",
  "ProtonsHub",
  "Providence",
  "Publicis Sapient",
  "Qodeleaf",
  "Qualcomm",
  "Quantiphi",
  "Quicket Solutions",
  "Qwikcilver Solutions",
  "Razorpay",
  "Richpanel",
  "Rohm Semiconduc tor India Pvt Ltd",
  "ROOTQUOTI ENT",
  "RootQuotien t Technologie s Private Limited",
  "Sabre Corporation",
  "Salesforce",
  "Samsung R&D Institute India",
  "Samsung Semiconduc tor India Research",
  "Sandvine",
  "SAP Labs",
  "Sapiens Technologie s",
  "Schaffler Technologies",
  "Schlumberg er",
  "Schneider Electric",
  "Sembly",
  "ShareChat",
  "Shell India",
  "Siemens EDA",
  "Silicon labs",
  "Slice",
  "Société Générale",
  "Solugenix",
  "Solutions Limited",
  "Sprinklr",
  "SquadStack",
  "Steradian Semiconduc tors Pvt Ltd",
  "Stratus Technologie s Pvt Ltd",
  "SWYM Corporation",
  "Systango",
  "Tata Digital",
  "Tata motors",
  "Tcs(NQT)",
  "Tech Mahindra",
  "Tekion",
  "Tekion India Private limited",
  "TelioLabs",
  "Texas instruments",
  "Thorogood Associates",
  "Tide platform",
  "Titan",
  "Titan Company Limited",
  "Toshiba",
  "Tower Research",
  "Tredence Analytics",
  "Trellix",
  "Trilogy Innovations (codenation)",
  "Uber",
  "UBS",
  "Udaan",
  "Uhnder india",
  "UHNDER INDIA PVT LTD",
  "Ultramarine and Pigments Ltd",
  "Urjanet - An Acardia Enterprise",
  "Vassar Labs",
  "Velocix Solutions",
  "Verizon",
  "Vicara",
  "Vikabh Securities Pvt Ltd",
  "Visa",
  "Visteon",
  "VMware",
  "Volvo",
  "Voxela, Inc.",
  "Walmart Global Tech India",
  "Wellsfargo",
  "Western Digital",
  "Wipro",
  "Wissen Technology",
  "WME",
  "Wolters Kluwer",
  "YantraVision",
  "Zee Entertainme nt",
  "Zenduty",
  "ZENTREELAB S",
  "Zignex",
  "Zomato",
  "ZS Associates",
  "ZScaler",
  "Zycus",
  "Zynga"]

  addToGlobalArray(data: any): void {
    this.globalArray.push(data);
  }
  constructor() { }
}
